steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/api-hut-kai-80", "."]
    dir: "Backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/api-hut-kai-80"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args: [
        "run",
        "deploy",
        "api-hut-kai-80",
        "--image",
        "gcr.io/$PROJECT_ID/api-hut-kai-80",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "asia-south1",
        "--allow-unauthenticated",
        "--set-env-vars",
        "ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET},REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET},DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_PASSWORD=${_DB_PASSWORD},DB_USERNAME=${_DB_USERNAME},ALLOWED_ORIGINS=${_ALLOWED_ORIGINS}",
        # "--set-secrets",
        # "fcm-service-account=fcm-service-account:latest",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "services",
        "add-iam-policy-binding",
        "api-hut-kai-80",
        "--member=allUsers",
        "--role=roles/run.invoker",
        "--region=asia-south1",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
