runtime: nodejs20
service: frontend-event-hut-kai-80
instance_class: F1

handlers:
  - url: /(.*\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))
    static_files: build/\1
    upload: build/(.*\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301

default_expiration: "1h"
